COS301-SE-2022/Map-out-game-reserves-using-aerial-photographs

- aerial-mapping/angular.json
- aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.html
- aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.scss
- aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.ts
- aerial-mapping/libs/client/shared/assets/.eslintrc.json
- aerial-mapping/libs/client/shared/assets/README.md
- aerial-mapping/libs/client/shared/assets/jest.config.ts
- aerial-mapping/libs/client/shared/assets/project.json
- aerial-mapping/libs/client/shared/assets/src/index.ts
- aerial-mapping/libs/client/shared/assets/src/lib/assets.module.ts
- aerial-mapping/libs/client/shared/assets/src/lib/global.scss
- aerial-mapping/libs/client/shared/assets/src/test-setup.ts
- aerial-mapping/libs/client/shared/assets/tsconfig.json
- aerial-mapping/libs/client/shared/assets/tsconfig.lib.json
- aerial-mapping/libs/client/shared/assets/tsconfig.spec.json
- aerial-mapping/tsconfig.base.json
> Create a global.scss

- aerial-mapping/libs/client/login/src/lib/client-login.module.ts
- aerial-mapping/libs/client/login/src/lib/login/login.component.html
- aerial-mapping/libs/client/login/src/lib/login/login.component.scss
Basics of the login page implemented
> ✨UI for the login page

- aerial-mapping/libs/client/login/src/lib/login/login.component.html
- aerial-mapping/libs/client/login/src/lib/login/login.component.scss
With the requirements from the clients, there is no longer a need to get from the login page to the registration page. The height of some elements have been changed to auto
> Login page: taking out register link and styling fixes

- aerial-mapping/apps/aerial-mapping/src/app/app.component.ts
- aerial-mapping/libs/api/shell/feature/src/lib/dashboard-repository.ts
- aerial-mapping/libs/client/shared/services/client-api.service.spec.ts
- aerial-mapping/libs/client/shared/services/client-api.service.ts
- aerial-mapping/package.json
- aerial-mapping/yarn.lock
-  Adding shared front-end API service in: libs > client > shared > services
> 🚧(ui): Adding shared front-end API service

- .github/workflows/full.yml
- .github/workflows/index.yml
- .github/workflows/meta.yml
- .github/workflows/nxtest.yml
> :white_check_mark: CICD: Updated workflows

- aerial-mapping/apps/api/src/app/schema.graphql
- aerial-mapping/libs/api/dashboard/feature/src/lib/api/dashboard.resolver.ts
- aerial-mapping/libs/api/dashboard/feature/src/lib/repository/dashboard-repository.ts
- aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.html
- aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.ts
- aerial-mapping/libs/client/shared/services/lib/client-api.service.ts
- aerial-mapping/prisma/migrations/20220512223235_1/migration.sql
- aerial-mapping/prisma/migrations/20220512232703_1/migration.sql
- aerial-mapping/prisma/migrations/20220512233017_1/migration.sql
- aerial-mapping/prisma/schema.prisma
> ✨(ui): Updated dashboard

- aerial-mapping/apps/api/src/app/schema.graphql
- aerial-mapping/libs/api/dashboard/feature/src/lib/api/dashboard.resolver.ts
- aerial-mapping/libs/api/dashboard/feature/src/lib/repository/dashboard-repository.ts
- aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.html
- aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.ts
- aerial-mapping/libs/client/shared/services/lib/client-api.service.ts
- aerial-mapping/prisma/migrations/20220512223235_1/migration.sql
- aerial-mapping/prisma/migrations/20220512232703_1/migration.sql
- aerial-mapping/prisma/migrations/20220512233017_1/migration.sql
- aerial-mapping/prisma/schema.prisma
Reverts COS301-SE-2022/Map-out-game-reserves-using-aerial-photographs#71
> Revert "Revert "✨(ui): Updated dashboard""

- aerial-mapping/apps/api/src/app/app.module.ts
- aerial-mapping/apps/api/src/app/schema.graphql
- aerial-mapping/apps/api/src/main.ts
- aerial-mapping/libs/api/dashboard/feature/README.md
- aerial-mapping/libs/api/dashboard/feature/src/lib/api/dashboard.resolver.spec.ts
- aerial-mapping/libs/api/dashboard/feature/src/lib/api/dashboard.resolver.ts
- aerial-mapping/libs/api/dashboard/feature/src/lib/repository/dashboard-repository.spec.ts
- aerial-mapping/libs/api/dashboard/feature/src/lib/repository/dashboard-repository.ts
- aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.ts
- aerial-mapping/libs/client/shared/services/lib/client-api.service.ts
- Added compatibility for the 'DateTime' type in the GraphQL schema
- Added a createVideoCollection front-end service function
- Added a createVideoCollection API schema mutation 
- Added a createVideoCollection API resolver
> 🚧(api): Adding DateTime scalar to the API

- aerial-mapping/libs/client/account/src/lib/account/account.component.html
- aerial-mapping/libs/client/account/src/lib/account/account.component.scss
- aerial-mapping/libs/client/account/src/lib/client-account.module.ts
The basic UI of the Accounts Page
> (ui): Accounts Page

- aerial-mapping/libs/client/account/src/lib/account/account.component.html
- aerial-mapping/libs/client/account/src/lib/account/account.component.scss
- aerial-mapping/libs/client/account/src/lib/account/account.component.spec.ts
- aerial-mapping/libs/client/account/src/lib/account/account.component.ts
- aerial-mapping/libs/client/account/src/lib/client-account.module.ts
The user is now able to edit their information in the database
> (ui): Accounts page edit pages

- aerial-mapping/apps/aerial-mapping/src/app/app-routing.module.ts
- aerial-mapping/apps/api/src/app/app.module.ts
- aerial-mapping/apps/api/src/app/schema.graphql
- aerial-mapping/libs/api/login/api/feature/src/lib/api-login-api-feature.module.ts
- aerial-mapping/libs/api/login/api/feature/src/lib/api-login-api.resolver.spec.ts
- aerial-mapping/libs/api/login/api/feature/src/lib/api-login-api.resolver.ts
- aerial-mapping/libs/api/login/repository/data-access/src/lib/api-login-repository-data-access.module.ts
- aerial-mapping/libs/api/login/repository/data-access/src/lib/api-login-repository-data-access.spec.ts
- aerial-mapping/libs/api/login/repository/data-access/src/lib/api-login-repository-data-access.ts
- aerial-mapping/libs/api/login/repository/data-access/src/lib/auth/guards/auth.guard.ts
- aerial-mapping/libs/api/register/api/feature/src/lib/api-register-api.resolver.spec.ts
- aerial-mapping/libs/api/register/api/feature/src/lib/api-register-api.resolver.ts
- aerial-mapping/libs/api/register/repository/data-access/src/lib/api-register-repository-data-access.spec.ts
- aerial-mapping/libs/api/register/repository/data-access/src/lib/api-register-repository-data-access.ts
- aerial-mapping/libs/api/shell/feature/src/lib/api-shell-feature.module.ts
- aerial-mapping/libs/client/account/src/lib/account/account.component.html
- aerial-mapping/libs/client/account/src/lib/account/account.component.spec.ts
- aerial-mapping/libs/client/account/src/lib/account/account.component.ts
- aerial-mapping/libs/client/account/src/lib/client-account.module.ts
- aerial-mapping/libs/client/login/src/index.ts
- aerial-mapping/libs/client/login/src/lib/auth/login.guard.ts
- aerial-mapping/libs/client/login/src/lib/client-login.module.ts
- aerial-mapping/libs/client/login/src/lib/login/login.component.html
- aerial-mapping/libs/client/login/src/lib/login/login.component.ts
- aerial-mapping/libs/client/register/src/lib/client-register.module.spec.ts
- aerial-mapping/libs/client/register/src/lib/client-register.module.ts
- aerial-mapping/libs/client/register/src/lib/register/register.component.html
- aerial-mapping/libs/client/register/src/lib/register/register.component.spec.ts
- aerial-mapping/libs/client/register/src/lib/register/register.component.ts
- aerial-mapping/libs/client/shared/services/lib/client-api.service.ts
- Added login validation on the backend
- Added JWT as cookie upon successful login
- Added AuthGuard to API routes to protect them (they require the JWT to be accessed)
- Added provisional LoginGuard to protect frontend angular view routes
- Added server-side JWT token validation (via API 'getAuthStatus')
- Added logout functionality (N.B. The logout button still needs styling)
- Added ability to send invites using the registration form on the account page
- Added registration functionality
> ✨(api/db/ui): Added Login/Logout and Registration

- aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.ts
Takes in a video and outputs the Images in Base64 format in an array
> ✨Splitting Video into Images

- aerial-mapping/libs/client/file-upload/src/lib/client-file-upload.module.ts
- aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.html
- aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.scss
- aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.ts
Adding a dropdown menu so when the pilot uploads media, he/she can specify from which park it came from
> Adding the park dropdown

- aerial-mapping/libs/api/image-catalogue/api/feature/.babelrc
- aerial-mapping/libs/api/image-catalogue/api/feature/.eslintrc.json
- aerial-mapping/libs/api/image-catalogue/api/feature/README.md
- aerial-mapping/libs/api/image-catalogue/api/feature/jest.config.js
- aerial-mapping/libs/api/image-catalogue/api/feature/project.json
- aerial-mapping/libs/api/image-catalogue/api/feature/src/index.ts
- aerial-mapping/libs/api/image-catalogue/api/feature/src/lib/api-image-catalogue-api-feature.module.ts
- aerial-mapping/libs/api/image-catalogue/api/feature/src/lib/api-image-catalogue-api.resolver.spec.ts
- aerial-mapping/libs/api/image-catalogue/api/feature/src/lib/api-image-catalogue-api.resolver.ts
- aerial-mapping/libs/api/image-catalogue/api/feature/tsconfig.json
- aerial-mapping/libs/api/image-catalogue/api/feature/tsconfig.lib.json
- aerial-mapping/libs/api/image-catalogue/api/feature/tsconfig.spec.json
- aerial-mapping/libs/api/image-catalogue/repository/data-access/.eslintrc.json
- aerial-mapping/libs/api/image-catalogue/repository/data-access/README.md
- aerial-mapping/libs/api/image-catalogue/repository/data-access/jest.config.js
- aerial-mapping/libs/api/image-catalogue/repository/data-access/project.json
- aerial-mapping/libs/api/image-catalogue/repository/data-access/src/index.ts
- aerial-mapping/libs/api/image-catalogue/repository/data-access/src/lib/api-image-catalogue-repository-data-access.module.ts
- aerial-mapping/libs/api/image-catalogue/repository/data-access/src/lib/api-image-catalogue-repository-data-access.spec.ts
- aerial-mapping/libs/api/image-catalogue/repository/data-access/src/lib/api-image-catalogue-repository-data-access.ts
- aerial-mapping/libs/api/image-catalogue/repository/data-access/tsconfig.json
- aerial-mapping/libs/api/image-catalogue/repository/data-access/tsconfig.lib.json
- aerial-mapping/libs/api/image-catalogue/repository/data-access/tsconfig.spec.json
- aerial-mapping/libs/api/s3-upload/api/feature/src/lib/api-s3-upload-api.resolver.ts
- aerial-mapping/libs/client/image-catalogue/src/lib/image-catalogue/image-catalogue.component.html
- aerial-mapping/libs/client/image-catalogue/src/lib/image-catalogue/image-catalogue.component.ts
- aerial-mapping/libs/client/shared/services/lib/client-api.service.ts
- aerial-mapping/package.json
- aerial-mapping/prisma/seed.ts
- Added image fetching for the Image Catalogue page from Amazon S3 bucket
- Added seed.ts to seed the database
- Added catalogue searching by date
> 🚧(ui): Displaying images on image catalogue

- aerial-mapping/apps/api/src/app/schema.graphql
- aerial-mapping/libs/api/dashboard/repository/data-access/src/lib/api-dashboard-repository-data-access.ts
- aerial-mapping/libs/api/login/api/feature/src/lib/api-login-api.resolver.ts
- aerial-mapping/libs/api/login/api/shared/interfaces/data-access/src/lib/api-login-entity.ts
- aerial-mapping/libs/api/login/repository/data-access/src/lib/api-login-repository-data-access.spec.ts
- aerial-mapping/libs/api/login/repository/data-access/src/lib/api-login-repository-data-access.ts
- aerial-mapping/libs/api/login/repository/data-access/src/lib/auth/guards/auth.guard.ts
- aerial-mapping/libs/api/register/api/feature/src/lib/api-register-api.resolver.spec.ts
- aerial-mapping/libs/api/register/api/feature/src/lib/api-register-api.resolver.ts
- aerial-mapping/libs/api/register/repository/data-access/src/lib/api-register-repository-data-access.spec.ts
- aerial-mapping/libs/api/register/repository/data-access/src/lib/api-register-repository-data-access.ts
- aerial-mapping/libs/client/account/src/lib/account/account.component.html
- aerial-mapping/libs/client/account/src/lib/account/account.component.ts
- aerial-mapping/libs/client/login/src/lib/client-login.module.spec.ts
- aerial-mapping/libs/client/login/src/lib/login/login.component.spec.ts
- aerial-mapping/libs/client/register/src/lib/register/register.component.ts
- aerial-mapping/libs/client/shared/services/lib/client-api.service.ts
- aerial-mapping/prisma/migrations/20220609132954_/migration.sql
- aerial-mapping/prisma/schema.prisma
- Fetched the currently logged-in user's email from the JWT.
- Populated the Account page UI with the currently logged-in user's details.
> 🚧(ui): Populating Account page with user details

- .github/workflows/nxtest.yml
- aerial-mapping/libs/client/account/jest.config.ts
- aerial-mapping/libs/client/account/src/lib/account/account.component.spec.ts
- aerial-mapping/libs/client/dashboard/jest.config.ts
- aerial-mapping/libs/client/dashboard/src/lib/client-dashboard.module.spec.ts
- aerial-mapping/libs/client/file-upload/jest.config.ts
- aerial-mapping/libs/client/login/jest.config.ts
- aerial-mapping/libs/client/map/src/lib/map-view/map-view.component.html
- aerial-mapping/libs/client/map/src/lib/map-view/map-view.component.ts
- aerial-mapping/libs/client/mapcollection/jest.config.ts
- aerial-mapping/libs/client/register/jest.config.ts
- aerial-mapping/libs/client/shared/assets/jest.config.ts
- aerial-mapping/libs/client/shared/components/footer/jest.config.ts
- aerial-mapping/libs/client/shared/components/navbar/jest.config.ts
Codecov is only uploading 11/23 files
> 🐛 (CICD): Trying to fix codecov

- aerial-mapping/libs/client/account/src/lib/account/account.component.html
- aerial-mapping/libs/client/account/src/lib/account/account.component.scss
- aerial-mapping/libs/client/dashboard/src/lib/bar-chart/bar-chart.component.html
- aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.html
- aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.scss
- aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.html
- aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.scss
- aerial-mapping/libs/client/login/src/lib/login/login.component.html
- aerial-mapping/libs/client/shared/assets/src/lib/global.scss
- Removing the password field from sending out a registration link
- Masking the password input field
- Adding an opaque brown colour
- Adjusting file upload spacing
- Fixing the chart on the dashboard as well as tile sizing
> Small UI changes

- aerial-mapping/apps/aerial-mapping/src/app/app-routing.module.ts
- aerial-mapping/apps/api/src/app/schema.graphql
- aerial-mapping/libs/api/dashboard/api/feature/src/lib/api-dashboard-api.resolver.ts
- aerial-mapping/libs/api/image-catalogue/api/feature/src/lib/api-image-catalogue-api.resolver.ts
- aerial-mapping/libs/api/login/api/feature/src/lib/api-login-api.resolver.ts
- aerial-mapping/libs/api/register/api/feature/src/lib/api-register-api.resolver.spec.ts
- aerial-mapping/libs/api/register/api/feature/src/lib/api-register-api.resolver.ts
- aerial-mapping/libs/api/register/repository/data-access/src/lib/api-register-repository-data-access.spec.ts
- aerial-mapping/libs/api/register/repository/data-access/src/lib/api-register-repository-data-access.ts
- aerial-mapping/libs/api/s3-upload/api/feature/src/lib/api-s3-upload-api.resolver.ts
- aerial-mapping/libs/api/s3-upload/repository/data-access/src/lib/api-s3-upload-repository-data-access.spec.ts
- aerial-mapping/libs/api/s3-upload/repository/data-access/src/lib/api-s3-upload-repository-data-access.ts
- Added authentication guards to necessary API endpoints
- Added authentication route guards to necessary front-end pages
- Added createFlight resolver
- Added getParkId resolver
> 🛂(api): Added Auth to necessary API endpoints and client routes

- aerial-mapping/angular.json
- aerial-mapping/libs/api/image-catalogue/api/feature/src/lib/api-image-catalogue-api.resolver.ts
- aerial-mapping/libs/api/register/api/feature/src/lib/api-register-api.resolver.ts
- aerial-mapping/prisma/seed.ts
- aerial-mapping/tsconfig.base.json
- Removed surname field from seed
> 🐛(db): Fixing seed.ts

- amplify/backend/api/amplifyapp/schema.graphql
- amplify/backend/backend-config.json
- amplify/backend/function/S3Triggerbfbfb03a/amplify.state
- amplify/backend/function/registerlinkemailer/registerlinkemailer-cloudformation-template.json
- amplify/backend/function/registerlinkemailer/src/index.js
- amplify/backend/types/amplify-dependent-resources-ref.d.ts
- amplify/team-provider-info.json
- angular.json
- src/app/API.service.ts
- src/app/api/controller/controller.service.ts
- src/app/components/account/account.component.ts
- src/graphql/queries.graphql
- src/graphql/schema.json
- src/models/schema.js
- Prepping the app config for a basic production build
> Adjusting Config for Production Build

- karma.conf.js
> CICD: Fixing codecov

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/components/account/account.component.html
- src/app/components/account/account.component.scss
- src/app/components/account/account.module.ts
- src/app/components/dashboard/dashboard.component.html
- src/app/components/dashboard/dashboard.component.scss
- src/app/components/file-upload/file-upload.component.html
- src/app/components/image-catalogue/image-catalogue.component.html
- src/app/components/map-collections/map-collections.component.html
- src/app/components/map-collections/map-collections.component.scss
- src/app/components/shared/navbar/navbar.component.html
- src/app/components/shared/navbar/navbar.component.scss
- src/app/components/shared/navbar/navbar.component.ts
- src/app/components/shared/navbar/navbar.module.ts
- src/styles.scss
Co-authored-by: Zoe Liebenberg <u20444738@tuks.co.za>
> 💄 (ui): UI NavBar restyle

- src/app/api/controller/controller.service.spec.ts
- src/app/app.module.ts
- src/app/components/image-catalogue/image-catalogue.module.ts
- src/app/components/register/register.component.spec.ts
Reverts COS301-SE-2022/Map-out-game-reserves-using-aerial-photographs#224
> Revert "✅(testing) Fixing API.service.ts"
